version: '3.7'

services:
  database:
    image: mongo:latest
    container_name: <% .ProjectName %>-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - net

volumes:
  mongodb_data:
