version: '3'
services:
  app:
    build: .
    container_name: <% .ProjectName %>
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database
    networks:
      - net

volumes:
  api:

networks:
  net:
    driver: bridge
